# Importation bibliothèques

In [59]:
import pandas as pd
import os
import time
from tqdm import tqdm  # barre de progression
import openmeteo_requests
import requests_cache
from retry_requests import retry
import gc

# Importation dataframe

Données qui viennent de Geoname

In [60]:
cols = [
    "geonameid", "name", "asciiname", "alternatenames",
    "latitude", "longitude", "feature_class", "feature_code",
    "country_code", "cc2", "admin1_code", "admin2_code",
    "admin3_code", "admin4_code", "population",
    "elevation", "dem", "timezone", "modification_date"
]

df_cities = pd.read_csv(r"C:\Users\Utilisateur\Desktop\ProjetCertif\ProjetCertif\DATA\raw\cities500.txt", sep="\t", names=cols)

C:\Users\Utilisateur\AppData\Local\Temp\ipykernel_9012\3533418009.py:9: DtypeWarning: Columns (0: cc2, 1: admin1_code, 2: admin3_code, 3: admin4_code) have mixed types. Specify dtype option on import or set low_memory=False.
  df_cities = pd.read_csv(r"C:\Users\Utilisateur\Desktop\ProjetCertif\ProjetCertif\DATA\raw\cities500.txt", sep="\t", names=cols)

In [44]:
df_cities.head()

,geonameid,name,asciiname,alternatenames,latitude,longitude,feature_class,feature_code,country_code,cc2,admin1_code,admin2_code,admin3_code,admin4_code,population,elevation,dem,timezone,modification_date
0,3038832,Vila,Vila,"Casas Vila,Vila",42.53176,1.56654,P,PPL,AD,NaN,03,NaN,NaN,NaN,1418,NaN,1318,Europe/Andorra,2024-11-04
1,3038999,Soldeu,Soldeu,"Sol'deu,Soldeu,surudeu,swldw,Сольдеу,סולדאו,سو...",42.57688,1.66769,P,PPL,AD,NaN,02,NaN,NaN,NaN,602,NaN,1832,Europe/Andorra,2017-11-06
2,3039077,Sispony,Sispony,Sispony,42.53368,1.51613,P,PPL,AD,NaN,04,NaN,NaN,NaN,833,NaN,1315,Europe/Andorra,2024-11-04
3,3039154,El Tarter,El Tarter,"Ehl Tarter,El Tarter,El Tarter - Principau d'A...",42.57952,1.65362,P,PPL,AD,NaN,02,NaN,NaN,NaN,1052,NaN,1721,Europe/Andorra,2012-11-03
4,3039163,Sant Julià de Lòria,Sant Julia de Loria,"San Julia,San Julià,Sant Julia de Loria,Sant J...",42.46372,1.49129,P,PPLA,AD,NaN,06,NaN,NaN,NaN,8022,NaN,921,Europe/Andorra,2013-11-23

Je selectionne les colonnes les plus pertinantes pour mon projet et je ne selectionne que les villes qui on plus de 100000 habitants.

In [45]:
df_ville = df_cities[['geonameid', 'name', 'asciiname', 'latitude', 'longitude', 'feature_code', 'country_code', 'population', 'timezone']]
df_ville = df_ville[df_ville["population"] > 100000]
df_ville.head()

,geonameid,name,asciiname,latitude,longitude,feature_code,country_code,population,timezone
20,290503,Warīsān,Warisan,25.16744,55.40708,PPL,AE,108759,Asia/Dubai
25,291074,Ras Al Khaimah,Ras Al Khaimah,25.78953,55.94320,PPLA,AE,351943,Asia/Dubai
34,292223,Dubai,Dubai,25.07725,55.30927,PPLA,AE,3790000,Asia/Dubai
37,292261,Dayrah,Dayrah,25.27143,55.30207,PPLX,AE,400000,Asia/Dubai
38,292672,Sharjah,Sharjah,25.33420,55.41221,PPLA,AE,1800000,Asia/Dubai

In [46]:
df_ville.info()

<class 'pandas.DataFrame'>
Index: 5986 entries, 20 to 230849
Data columns (total 9 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   geonameid     5986 non-null   int64
 1   name          5986 non-null   str
 2   asciiname     5986 non-null   str
 3   latitude      5986 non-null   float64
 4   longitude     5986 non-null   float64
 5   feature_code  5986 non-null   str
 6   country_code  5985 non-null   str
 7   population    5986 non-null   int64
 8   timezone      5986 non-null   str
dtypes: float64(2), int64(2), str(5)
memory usage: 467.7 KB

# Exportation des données

In [47]:
output_dir = "../DATA/processed"
os.makedirs(output_dir, exist_ok=True)

df_ville.to_csv(os.path.join(output_dir, "villes.csv"))