# Importation bibliothèques

In [18]:
import pandas as pd
import os

# Importations dataframes

In [4]:
df_lexique = pd.read_csv(r"C:\Users\Utilisateur\Desktop\ProjetCertif\ProjetCertif\DATA\processed\iso3166.csv")
df_wtd = pd.read_csv(r"C:\Users\Utilisateur\Desktop\ProjetCertif\ProjetCertif\DATA\processed\Kaggle_WorldTravelDestination.csv")

In [5]:
df_lexique.columns

Index(['pays', 'code_2L', 'code_3L', 'code_numerique'], dtype='str')

In [10]:
df_wtd.head()

,Unnamed: 0,id,City,country,region,short_description,latitude,longitude,budget_level,culture,...,temp_month9_min,temp_month10_avg,temp_month10_max,temp_month10_min,temp_month11_avg,temp_month11_max,temp_month11_min,temp_month12_avg,temp_month12_max,temp_month12_min
0,0,c54acf38-3029-496b-8c7a-8343ad82785c,Milan,Italy,europe,"Chic streets lined with fashion boutiques, his...",45.464194,9.189635,3,5,...,16.1,15.2,19.6,11.5,8.8,12.5,5.6,4.7,8.2,1.9
1,1,0bd12654-ed64-424e-a044-7bc574bcf078,Yasawa Islands,Fiji,oceania,"Crystal-clear waters, secluded beaches, and vi...",-17.290947,177.125786,3,2,...,24.5,26.0,30.5,19.0,27.1,31.0,24.8,28.2,31.9,26.0
2,2,73036cda-9134-46fc-a2c6-807782d59dfb,Whistler,Canada,north_america,Snow-capped peaks and lush forests create a se...,50.117190,-122.954302,3,3,...,9.9,7.6,11.6,4.4,1.8,5.1,-1.6,-1.8,0.9,-2.5
3,3,3872c9c0-6b6e-49e1-9743-f46bfe591b86,Guanajuato,Mexico,north_america,Winding cobblestone streets and colorful facad...,20.987700,-101.000000,2,5,...,13.9,19.0,26.2,12.6,17.7,25.5,10.7,14.9,22.1,9.2
4,4,e1ebc1b6-8798-422d-847a-22016faff3fd,Surabaya,Indonesia,asia,Bustling streets filled with the aroma of loca...,-7.245972,112.737827,1,4,...,25.4,29.8,35.1,26.2,29.6,34.0,26.4,28.7,33.2,25.8

# Mise à jour des colonnes
Je les mets toutes en minuscules pour pouvoir garentir un merge de _qualité_

In [13]:
df_lexique["pays"] = df_lexique["pays"].str.lower()
df_wtd["country"] = df_wtd["country"].str.lower()

# Merge

In [14]:
df_merge = pd.merge(df_lexique, df_wtd, left_on="pays", right_on="country", how="inner")
df_merge

,pays,code_2L,code_3L,code_numerique,Unnamed: 0,id,City,country,region,short_description,...,temp_month9_min,temp_month10_avg,temp_month10_max,temp_month10_min,temp_month11_avg,temp_month11_max,temp_month11_min,temp_month12_avg,temp_month12_max,temp_month12_min
0,france,FR,FRA,250,80,caf79b01-70b6-450b-9601-66fdadb8df39,Marseille,france,europe,"A lively port city with Mediterranean flair, b...",...,16.5,17.2,22.3,12.8,12.0,16.5,8.1,8.8,13.5,4.8
1,france,FR,FRA,250,89,3a70dff6-b805-4e41-accf-480d43ed6ba7,Annecy,france,europe,Charming canals and cobblestone streets weave ...,...,10.9,12.3,17.8,7.8,6.8,10.9,3.2,3.2,6.8,0.3
2,france,FR,FRA,250,166,ddea7cd4-1b80-46f6-a51d-2649a27cba85,Nantes,france,europe,A city where historic charm meets modern creat...,...,12.5,13.8,18.5,9.9,9.5,13.5,6.2,7.7,10.8,4.9
3,france,FR,FRA,250,228,04624f1d-9d64-4b83-a228-9914ef03c43e,Bordeaux,france,europe,"Strolling through sun-dappled streets, you'll ...",...,14.1,15.2,20.5,11.2,10.5,14.9,7.2,8.3,12.2,5.5
4,france,FR,FRA,250,229,4b7bab82-52b8-4827-a591-750c48a47f39,Strasbourg,france,europe,Charming cobblestone streets lined with half-t...,...,11.4,12.0,17.4,7.7,6.8,10.2,3.8,4.4,7.4,1.9
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
100,vietnam,VN,VNM,704,418,dca139e8-a2d8-4edc-a494-bb831291452e,Hanoi,vietnam,asia,Bustling streets filled with the aroma of stre...,...,25.5,25.9,29.6,22.7,23.4,27.2,20.2,18.6,22.3,15.7
101,vietnam,VN,VNM,704,516,63063324-d84d-44b2-9329-8f80e881d2db,Hue,vietnam,asia,Ancient temples and serene riverside views off...,...,24.7,25.7,29.0,23.4,24.4,27.7,22.0,21.0,23.4,19.0
102,vietnam,VN,VNM,704,518,7cca7133-fa5c-4ef8-bf83-f9a9221130cb,Ha Long,vietnam,asia,Misty limestone karsts rise dramatically from ...,...,24.8,24.8,28.5,21.6,22.6,27.2,19.5,17.8,22.2,14.4
103,zimbabwe,ZW,ZWE,716,449,e570ec15-1d11-49e6-8a55-1243633a8668,Harare,zimbabwe,africa,"Vibrant streets filled with colorful markets, ...",...,12.8,22.4,29.0,15.0,22.3,28.3,16.8,22.1,27.5,17.2
104,réunion,RE,REU,638,159,7f92c683-b2a3-4058-a2dc-758c1d230a26,Saint-Denis,réunion,africa,"A lively mix of Creole culture, bustling marke...",...,19.1,23.8,27.7,20.3,25.0,28.8,21.6,26.4,30.4,23.1

In [16]:
df_merge.info()

<class 'pandas.DataFrame'>
RangeIndex: 105 entries, 0 to 104
Data columns (total 63 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   pays               105 non-null    str
 1   code_2L            105 non-null    str
 2   code_3L            105 non-null    str
 3   code_numerique     105 non-null    int64
 4   Unnamed: 0         105 non-null    int64
 5   id                 105 non-null    str
 6   City               105 non-null    str
 7   country            105 non-null    str
 8   region             105 non-null    str
 9   short_description  105 non-null    str
 10  latitude           105 non-null    float64
 11  longitude          105 non-null    float64
 12  budget_level       105 non-null    int64
 13  culture            105 non-null    int64
 14  adventure          105 non-null    int64
 15  nature             105 non-null    int64
 16  beaches            105 non-null    int64
 17  nightlife          105 non-null    int64
 18  cuisine            105 non-null    int64
 19  wellness           105 non-null    int64
 20  urban              105 non-null    int64
 21  seclusion          105 non-null    int64
 22  Day trip           105 non-null    int64
 23  Long trip          105 non-null    int64
 24  One week           105 non-null    int64
 25  Short trip         105 non-null    int64
 26  Weekend            105 non-null    int64
 27  temp_month1_avg    105 non-null    float64
 28  temp_month1_max    105 non-null    float64
 29  temp_month1_min    105 non-null    float64
 30  temp_month2_avg    105 non-null    float64
 31  temp_month2_max    105 non-null    float64
 32  temp_month2_min    105 non-null    float64
 33  temp_month3_avg    105 non-null    float64
 34  temp_month3_max    105 non-null    float64
 35  temp_month3_min    105 non-null    float64
 36  temp_month4_avg    105 non-null    float64
 37  temp_month4_max    105 non-null    float64
 38  temp_month4_min    105 non-null    float64
 39  temp_month5_avg    105 non-null    float64
 40  temp_month5_max    105 non-null    float64
 41  temp_month5_min    105 non-null    float64
 42  temp_month6_avg    105 non-null    float64
 43  temp_month6_max    105 non-null    float64
 44  temp_month6_min    105 non-null    float64
 45  temp_month7_avg    105 non-null    float64
 46  temp_month7_max    105 non-null    float64
 47  temp_month7_min    105 non-null    float64
 48  temp_month8_avg    105 non-null    float64
 49  temp_month8_max    105 non-null    float64
 50  temp_month8_min    105 non-null    float64
 51  temp_month9_avg    105 non-null    float64
 52  temp_month9_max    105 non-null    float64
 53  temp_month9_min    105 non-null    float64
 54  temp_month10_avg   105 non-null    float64
 55  temp_month10_max   105 non-null    float64
 56  temp_month10_min   105 non-null    float64
 57  temp_month11_avg   105 non-null    float64
 58  temp_month11_max   105 non-null    float64
 59  temp_month11_min   105 non-null    float64
 60  temp_month12_avg   105 non-null    float64
 61  temp_month12_max   105 non-null    float64
 62  temp_month12_min   105 non-null    float64
dtypes: float64(38), int64(17), str(8)
memory usage: 51.8 KB

# Extraction des données

In [17]:
worldtraveldestination_iso = df_merge

In [19]:
output_dir = "../DATA/processed"
os.makedirs(output_dir, exist_ok=True)

# Base de données déscriptives
worldtraveldestination_iso.to_csv(os.path.join(output_dir, "WorldTravel_ISO.csv"))