In [1]:
import pandas as pd

In [3]:
df_worldbank = pd.read_csv(r"..\DATA\external\donnees_touriste.csv")

In [4]:
df_worldbank.head()

,pays,Services voyage (% exports de services),Accès électricité (% pop),Densité de population (hab/km²),Pop. dans grandes agglomérations (%),Accès Internet (% pop),PIB par habitant (USD),Accès eau potable (% pop),Médecins (pour 1000 habitants),Dépenses santé par habitant (USD),...,Espérance de vie (années),Population rurale (% total),Population urbaine (% total),Arrivées touristes internationaux (nb),Départs touristes internationaux (nb),Recettes tourisme (USD),Recettes tourisme (% exportations),Recettes voyages touristiques (USD),Dépenses tourisme (USD),date_maj
0,AGO,9.923331,51.1,29.477746,25.285333,44.7581,2916.136633,67.224425,0.244,76.071182,...,64.617000,30.148497,69.851503,218000.0,NaN,1.900000e+07,0.090457,1.600000e+07,6.910000e+08,2026-03-26
1,BDI,2.372476,11.6,533.078271,NaN,11.0784,250.627253,65.806988,0.078,28.140289,...,63.651000,76.446523,23.553477,299000.0,NaN,3.700000e+06,1.570029,3.900000e+06,4.900000e+07,2026-03-26
2,BGD,7.113293,99.5,1319.179797,16.673341,44.5027,2551.017738,98.681668,0.722,53.464325,...,74.672000,67.842153,32.157847,323000.0,1.460000e+06,2.179000e+08,0.566327,2.170000e+08,6.590000e+08,2026-03-26
3,BWA,69.432982,76.0,4.376412,NaN,81.3600,7826.353765,91.723655,0.379,489.596771,...,69.163000,32.978734,67.021266,1830000.0,NaN,2.170000e+08,4.561363,2.110000e+08,9.180000e+07,2026-03-26
4,CAN,29.408235,100.0,4.560798,44.802126,93.9564,54220.328504,98.290504,2.819,6186.652344,...,81.646585,17.474944,82.525056,32430000.0,3.784590e+07,1.999400e+10,3.656701,1.125600e+10,4.124700e+10,2026-03-26

In [6]:
df_worldbank.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 41 entries, 0 to 40
Data columns (total 24 columns):
 #   Column                                   Non-Null Count  Dtype
---  ------                                   --------------  -----
 0   pays                                     41 non-null     object
 1   Services voyage (% exports de services)  38 non-null     float64
 2   Accès électricité (% pop)                41 non-null     float64
 3   Densité de population (hab/km²)          41 non-null     float64
 4   Pop. dans grandes agglomérations (%)     25 non-null     float64
 5   Accès Internet (% pop)                   40 non-null     float64
 6   PIB par habitant (USD)                   41 non-null     float64
 7   Accès eau potable (% pop)                40 non-null     float64
 8   Médecins (pour 1000 habitants)           40 non-null     float64
 9   Dépenses santé par habitant (USD)        40 non-null     float64
 10  Pauvreté < 3$/jour (% pop)               35 non-null     float64
 11  Pauvreté seuil national (% pop)          34 non-null     float64
 12  Revenu 40% les plus pauvres ($/jour)     26 non-null     float64
 13  Revenu moyen par habitant ($/jour)       26 non-null     float64
 14  Espérance de vie (années)                41 non-null     float64
 15  Population rurale (% total)              41 non-null     float64
 16  Population urbaine (% total)             41 non-null     float64
 17  Arrivées touristes internationaux (nb)   40 non-null     float64
 18  Départs touristes internationaux (nb)    22 non-null     float64
 19  Recettes tourisme (USD)                  37 non-null     float64
 20  Recettes tourisme (% exportations)       36 non-null     float64
 21  Recettes voyages touristiques (USD)      39 non-null     float64
 22  Dépenses tourisme (USD)                  37 non-null     float64
 23  date_maj                                 41 non-null     object
dtypes: float64(22), object(2)
memory usage: 7.8+ KB

In [7]:
df_meteo = pd.read_csv(r"..\DATA\processed\meteo.csv")

In [8]:
df_meteo.head()

    City country code_3L  month  temp_avg  temp_max  temp_min
0  Accra   ghana     GHA      1      28.7      33.3      25.8
1  Accra   ghana     GHA     10      27.3      31.1      24.4
2  Accra   ghana     GHA     11      28.4      32.4      25.2
3  Accra   ghana     GHA     12      28.8      33.2      25.7
4  Accra   ghana     GHA      2      29.1      33.6      26.3

In [9]:
df_meteo.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1248 entries, 0 to 1247
Data columns (total 7 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   City      1248 non-null   object
 1   country   1248 non-null   object
 2   code_3L   1248 non-null   object
 3   month     1248 non-null   int64
 4   temp_avg  1248 non-null   float64
 5   temp_max  1248 non-null   float64
 6   temp_min  1248 non-null   float64
dtypes: float64(3), int64(1), object(3)
memory usage: 68.4+ KB

In [10]:
df_lifequality = pd.read_csv(r"..\DATA\processed\life_quality.csv")

In [11]:
df_lifequality.head()

,Classement,Pays,Indice de Qualité de Vie,Indice du Pouvoir d'Achat,Indice de Sécurité,Indice des soins de santé,Indice du Coût de la Vie,Rapport Prix de l'immobilier/Revenu,Indice du Temps de Trajet dans Trafic,Indice de pollution,Indice Climatique
0,NaN,Luxembourg,219.32,182.53,65.72,75.33,62.43,8.88,27.18,23.27,82.62
1,NaN,Pays-Bas,207.48,124.91,73.58,79.28,63.12,7.69,23.48,21.38,87.01
2,NaN,Danemark,205.57,127.20,73.89,78.47,72.27,6.58,27.81,20.75,83.74
3,NaN,Oman,204.30,139.80,81.77,65.11,42.37,2.88,20.96,35.04,67.22
4,NaN,Suisse,203.95,158.68,73.91,71.73,101.10,10.40,32.93,23.31,82.04

In [12]:
df_lifequality.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 83 entries, 0 to 82
Data columns (total 11 columns):
 #   Column                                 Non-Null Count  Dtype
---  ------                                 --------------  -----
 0   Classement                             0 non-null      float64
 1   Pays                                   83 non-null     object
 2   Indice de Qualité de Vie               83 non-null     float64
 3   Indice du Pouvoir d'Achat              83 non-null     float64
 4   Indice de Sécurité                     83 non-null     float64
 5   Indice des soins de santé              83 non-null     float64
 6   Indice du Coût de la Vie               83 non-null     float64
 7   Rapport Prix de l'immobilier/Revenu    83 non-null     float64
 8   Indice du Temps de Trajet dans Trafic  83 non-null     float64
 9   Indice de pollution                    83 non-null     float64
 10  Indice Climatique                      83 non-null     float64
dtypes: float64(10), object(1)
memory usage: 7.3+ KB

In [13]:
df_iso = pd.read_csv(r"..\DATA\processed\iso3166.csv")

In [14]:
df_iso.head()

        pays code_2L code_3L  code_numerique
0  ALLEMAGNE      DE     DEU             276
1   AUTRICHE      AT     AUT              40
2   BELGIQUE      BE     BEL              56
3   BULGARIE      BG     BGR             100
4     CHYPRE      CY     CYP             196

In [15]:
df_iso.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 220 entries, 0 to 219
Data columns (total 4 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   pays            220 non-null    object
 1   code_2L         219 non-null    object
 2   code_3L         220 non-null    object
 3   code_numerique  220 non-null    int64
dtypes: int64(1), object(3)
memory usage: 7.0+ KB